services:
  - type: web
    name: shoova-one-backend
    runtime: python
    plan: starter
    region: oregon
    buildCommand: |
      chmod +x render-build.sh
      ./render-build.sh
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SUPERADMIN_EMAIL
        value: admin@shoova.org
      - key: SUPERADMIN_FIRST_NAME
        value: Super
      - key: SUPERADMIN_LAST_NAME
        value: Admin
      - key: SUPERADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: shoova_one_db
          property: connectionString
    databases:
      - name: shoova_one_db
        databaseName: shoova_one
        user: shoova